### ISSUE TITLE
0.1 Release of AI Ecosystem extension

### ISSUE THREAD

**Issue by cholmes** [fiboa/ai-ecosystem-extension#2]
Let's get the first release of the AI Ecosystem extension out! 

This issue should likely evolve to be a 'milestone' with a few sub-issues. But this can serve as the start:

- [x] update name of repo to include `-extension` in the name, like `ai-ecosystem-extension`, though could go simpler with just like `ai-extension`?
- [x] Update geojson and geoparquet examples to show the extension properties and actually validate against both fiboa core spec and the extension
- [x] Update readmes to follow good best practices for getting started.

- [x] Breakout discussion

**Comment by jacobsn** [comment]
Tagging @eddiechoi00. This is probably a good issue for him to focus on as part of his work supporting the Fieldscapes dataset construction.

**Comment by m-mohr** [comment]
Done :-)
